version: 0.0
os: linux
files:
  - source: /API_5322/
    destination: /var/www/API_5322
  - source: scripts/API_5322.conf
    destination: /etc/httpd/conf.d/
  - source: scripts/API_5322.service
    destination: /etc/systemd/system/

hooks:
  ApplicationStop:
    - location: scripts/stop_service
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/remove_application
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_service
      timeout: 300
      runas: root